name: tests
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  tests:
    strategy:
      matrix:
<<<<<<< HEAD
        python: ['3.9', '3.10', '3.11', '3.12']
=======
        python: [3.14]
>>>>>>> 1d00365ffa06bce9e994e8d120150c6aa0debdde
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run linter
        run: |
          pip3 install flake8 pep8-naming
          flake8 .
      - name: Run tests
        run: |
          python -m pytest --doctest-modules src tests
